from typing import Protocol, List

class IExcelRepository(Protocol):
    def read_sheets(self, path_name_excel: str, sheet_names: List[str], nrows: int = 4, engine: str = 'calamine'):
        ...
    def read_columns(self, path_name_excel: str, sheet_name: str, col_indexes: List[int], skiprows: int = 3, engine: str = 'calamine'):
        ...

class IFileRepository(Protocol):
    def ensure_dir(self, path: str) -> None:
        ...
    def list_files(self, path: str, extensions: List[str]) -> List[str]:
        ...
    def write_text(self, file_path: str, content: str) -> None:
        ...
    def append_text(self, file_path: str, content: str) -> None:
        ...
